### ISSUE TITLE
Switching from create react app buildpack. Problem on step 2.

### ISSUE THREAD

**Issue by rokit** [mars/heroku-cra-node#11]
I am following the steps to switch from `create-react-app-buildpack`. When I get to step 2 and run this:
`git mv [!react-ui]* react-ui/`
instead of seeing:
`fatal: Not a git repository`
I see this:
`fatal: bad source, source=[!react-ui]*, destination=react-ui/[!react-ui]*`

**Edit:**
Maybe this is the problem?
https://superuser.com/questions/1050326/git-mv-returns-bad-source-in-powershell

If that is the case, is there any harm in moving the files manually? I'm not that knowledgeable of git and what can break it.

**Comment by mars** [comment]
You can definitely move the files manually. Really it's simpler than that command looks:

1. create a `react-ui` directory
2. copy everything into that directory except the `.git` directory

**Comment by rokit** [comment]
Cool, thanks.
