### ISSUE TITLE
Unnecessary polyfill

### ISSUE THREAD

**Issue by Timer** [mars/heroku-cra-node#2]
[Polyfilling `fetch`](https://github.com/mars/heroku-cra-node/blob/a0500c5476b727e937271b80cdfab144abd85c53/react-ui/src/App.js#L3) is unnecessary, `create-react-app` already does so [among others](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/config/polyfills.js).

**Comment by mars** [comment]
Good to know. Feel free to open a pull request. Otherwise, I'll get around to it eventually.
