### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by gaetanozappi** [mars/heroku-cra-node#22]
@mars : Hi, congratulations on the module.
I was trying it, I wanted to know if it was possible to do certain things like these and how to do them:
1) Create multiple pages, for example.
/ -> App.js
/home -> home.js
/local -> local.js
2) To be able to set via nodejs or react:
- the page title
- icon
- variable passed through get in nodejs and then used in react.
3) Install external modules both on nodejs and on react.

**Comment by mars** [comment]
Thanks for reaching out 😄 I understand how answering these questions is integral to building a new app, but the goal of this project is to **simply illustrate using create-react-app + Node server as a Heroku app.** This project is never going to address general techniques for building a web app, unless folks start contributing `examples/` via pull request 🙏 

Regarding,

> 3. Install external modules both on nodejs and on react.

I did just update the README to clarify [how to install new npm packages in both Node and React](https://github.com/mars/heroku-cra-node/blob/master/README.md#user-content-local-development).
