### ISSUE TITLE
"All remaining requests return the React app, so it can handle routing"

### ISSUE THREAD

**Issue by maulberto3** [mars/heroku-cra-node#26]
That line is a comment inside the server's package.json. I want to know what that line means? Are you referring to React Router routing or Express routing?

**Comment by mars** [comment]
That comment is in [`server/index.js`](https://github.com/mars/heroku-cra-node/blob/master/server/index.js#L33), and it means that the Express route on the next line will handle all GET requests (that have not already been handled by an Express route above it) to the React app by sending `index.html` to the browser. Whether or not the React app uses React Router for routing is up to you.

**Comment by maulberto3** [comment]
@mars I see, thank you.
