### ISSUE TITLE
git mv -k [!react-ui]* react-ui/

### ISSUE THREAD

**Issue by tcpaul** [mars/heroku-cra-node#27]
git mv -k [!react-ui]* react-ui/

this does not work in zsh, I just switch to bash and it works

Some folks have reported problems with these commands. Sorry if they do not work for you, know that the point is to move everything in the repo into the react-ui/ subdirectory. Except for .git/ which should remain at the root level.

**Comment by mars** [comment]
This is a known challenge, as the README explains.

No need to open an issue about it.

**Comment by tcpaul** [comment]
sorry I was suggesting the readme should suggest switching to bash, maybe i can make a pull request instead

**Comment by mars** [comment]
I added a little note about using `bash`. Hopefully it will help more folks with this remarkably simple but challenging step 😅
