### ISSUE TITLE
API call failed: fresh install

### ISSUE THREAD

**Issue by marclundgren** [mars/heroku-cra-node#31]
1. fresh clone & install & start
```
hub clone mars/heroku-cra-node
cd heroku-cra-node/
npm install && npm start

# in a new tab
cd heroku-cra-node/react-ui
npm install && npm start
```

2. load localhost:3000

3. assert the api request to `/api` fails as 404

<img width="1381" alt="screen shot 2018-10-06 at 5 04 26 pm" src="https://user-images.githubusercontent.com/1154834/46576851-22b8b400-c98a-11e8-9cb4-98a82c01b999.png">

## question
Did I miss a step somewhere?

**Comment by mars** [comment]
Does the server start-up successfully?

What is logged in the terminal from the server process as it starts and then during those failing requests?

**Comment by marclundgren** [comment]
@mars yup. the server was down - sorry i forgot to check that
