### ISSUE TITLE
unable to find the index.html

### ISSUE THREAD

**Issue by pritisolanki** [mars/heroku-cra-node#32]
Hi,

I have followed the step to deploy create react app + node js and getting following error
Could not find a required file. 
Jan 08 20:01:55 bu-admin-app app/web.1:   Name: index.html 
Jan 08 20:01:55 bu-admin-app app/web.1:   Searched in: /app/public 

As I moved the public and src folder insider react-ui this will happen. Do I miss any other setting for react so that it search in /app/react-ui/public instead of app/public .

**Comment by WobWainwwight** [comment]
I have a similar problem: 

remote:        Could not find a required file.
remote:          Name: index.html
remote:          Searched in: /tmp/build_63f869097626bedb8342ed07ae1a2e4c/react-ui/public

Thanks for any help!

**Comment by mars** [comment]
Hi folks 👋

Since this app works as provided, something has been changed in each of your cases to prevent the index.html from being found.

My guess is that you've moved/renamed the `react-ui/` directory. Try naming the React app directory back to `react-ui/` and then it should work again.
