### ISSUE TITLE
Could use a command to run locally

### ISSUE THREAD

**Issue by danielbrauer** [mars/heroku-cra-node#38]
This configuration is great for deploying to Heroku, but it would be really useful to have support for testing locally, using a development server for the frontend and running both that and the server simultaneously.

**Comment by mars** [comment]
Local development is already documented on the README:
https://github.com/mars/heroku-cra-node/blob/master/README.md#user-content-local-development

**Comment by danielbrauer** [comment]
Ideally there would be one command for running both, but I can see why you'd want to keep it simple.

Shouldn't the static static portion of the Node server at least be conditional on whether it's running in a production environment?

**Comment by mars** [comment]
> Shouldn’t the static site…

Please elaborate on what you’re trying to solve. You can definitely change it to fit your needs. This is only a super simple starting point to see how CRA & Node can fit together as a Heroku app.
