### ISSUE TITLE
Heroku: Failed to load resource: the server responded with a status of 503 (Service Unavailable) /favicon.ico

### ISSUE THREAD

**Issue by albertothedev** [mars/heroku-cra-node#39]
I get this error everytime I open the app on Heroku. I have tried using [serve-favicon](https://www.npmjs.com/package/serve-favicon) but it doesn't seem to work.
[Here](https://github.com/albertothedev/snake-cra) is my repo.

**Comment by mars** [comment]
Hi @albertothedev 😄

HTTP status **503** typically means your app is crashed not able to serve requests. If there's a platform incident/outage happening at Heroku, then that could temporarily cause 503 responses as well. See: [Heroku Status](https://status.heroku.com/).

What do the `heroku logs` show for the app? Is it crashing? What is causing it to crash? If it started crashing when you implemented **serve-favicon**, then look into how your code is working, perhaps researching or opening an issue with that package.

This is not a problem with this example repo, but an issue with the code/implementation. Closing.
