### ISSUE TITLE
JS_RUNTIME_TARGET_BUNDLE missing quotes

### ISSUE THREAD

**Issue by keswatt** [mars/heroku-cra-node#40]
In README.md change from (no quotes):

    2. Set the bundle location for runtime config injection:
        heroku config:set JS_RUNTIME_TARGET_BUNDLE=/app/react-ui/build/static/js/*.js

to (added quotes):

    2. Set the bundle location for runtime config injection:
        heroku config:set JS_RUNTIME_TARGET_BUNDLE="/app/react-ui/build/static/js/*.js"

**Comment by mars** [comment]
Thanks. Good catch!

Revised it to use single quotes, since the glob should not be evaluated until it’s used in the dyno runtime.
