### ISSUE TITLE
compression not working

### ISSUE THREAD

**Issue by rickithadi** [mars/heroku-cra-node#46]
running a lighthouse audit gives a very poor performance rating(in single digits). Is compression enabled for the for the react front end?

**Comment by mars** [comment]
This example app is made to present a minimal app that builds & runs using Heroku, a starting point for Heroku deployment.


Everything this example app does is [right there in the JavaScript code](https://github.com/mars/heroku-cra-node/blob/master/server/index.js).

Setup [Express with compression](https://github.com/expressjs/compression) if you desire… it's not part of this all-in-one design example.
