### ISSUE TITLE
Heroku Deployment (CRACO)

### ISSUE THREAD

**Issue by ferick8246** [mars/heroku-cra-node#52]
Hello I keep getting this error in Heroku when I try to deploy can't get it to build correctly and we don't know what we are doing wrong. it's a MERN app using tailwind CSS and CRACO

`-----> Building on the Heroku-20 stack
-----> Using buildpacks:
       1. heroku/nodejs
       2. https://github.com/mars/heroku-cra-node
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 14.x...
       Downloading and installing node 14.17.4...
       Using default npm version: 6.14.14
       
-----> Restoring cache
       - node_modules
       
-----> Installing dependencies
       Installing node modules
       
       > scissors-palace@0.1.0 install /tmp/build_cc6cc312
       > cd server && npm i && cd ../react-ui && npm i && cd ../server && npm run seed
       
       
       > bcrypt@5.0.1 install /tmp/build_cc6cc312/server/node_modules/bcrypt
       > node-pre-gyp install --fallback-to-build
       
       [bcrypt] Success: "/tmp/build_cc6cc312/server/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" is installed via remote
       
       > core-js-pure@3.16.0 postinstall /tmp/build_cc6cc312/server/node_modules/core-js-pure
       > node -e "try{require('./postinstall')}catch(e){}"
       
       
       > @apollo/protobufjs@1.2.2 postinstall /tmp/build_cc6cc312/server/node_modules/@apollo/protobufjs
       > node scripts/postinstall
       
       added 269 packages from 359 contributors and audited 383 packages in 9.49s
       
       32 packages are looking for funding
         run `npm fund` for details
       
       found 0 vulnerabilities
       
       
       > @fortawesome/fontawesome-common-types@0.2.36 postinstall /tmp/build_cc6cc312/react-ui/node_modules/@fortawesome/fontawesome-common-types
       > node attribution.js
       
       Font Awesome Free 0.2.36 by @fontawesome - https://fontawesome.com
       License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
       
       
       > core-js@2.6.12 postinstall /tmp/build_cc6cc312/react-ui/node_modules/babel-runtime/node_modules/core-js
       > node -e "try{require('./postinstall')}catch(e){}"
       
       
       > core-js@3.16.0 postinstall /tmp/build_cc6cc312/react-ui/node_modules/core-js
       > node -e "try{require('./postinstall')}catch(e){}"
       
       
       > core-js-pure@3.16.0 postinstall /tmp/build_cc6cc312/react-ui/node_modules/core-js-pure
       > node -e "try{require('./postinstall')}catch(e){}"
       
       
       > ejs@2.7.4 postinstall /tmp/build_cc6cc312/react-ui/node_modules/ejs
       > node ./postinstall.js
       
       
       > @fortawesome/fontawesome-svg-core@1.2.36 postinstall /tmp/build_cc6cc312/react-ui/node_modules/@fortawesome/fontawesome-svg-core
       > node attribution.js
       
       Font Awesome Free 1.2.36 by @fontawesome - https://fontawesome.com
       License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
       
       
       > @fortawesome/free-brands-svg-icons@5.15.4 postinstall /tmp/build_cc6cc312/react-ui/node_modules/@fortawesome/free-brands-svg-icons
       > node attribution.js
       
       Font Awesome Free 5.15.4 by @fontawesome - https://fontawesome.com
       License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
       
       
       > @fortawesome/free-regular-svg-icons@5.15.4 postinstall /tmp/build_cc6cc312/react-ui/node_modules/@fortawesome/free-regular-svg-icons
       > node attribution.js
       
       Font Awesome Free 5.15.4 by @fontawesome - https://fontawesome.com
       License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
       
       
       > @fortawesome/free-solid-svg-icons@5.15.4 postinstall /tmp/build_cc6cc312/react-ui/node_modules/@fortawesome/free-solid-svg-icons
       > node attribution.js
       
       Font Awesome Free 5.15.4 by @fontawesome - https://fontawesome.com
       License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
       
       added 1923 packages from 806 contributors in 52.925s
       
       153 packages are looking for funding
         run `npm fund` for details
       
       
       > server@1.0.0 seed /tmp/build_cc6cc312/server
       > node config/seeds.js
       
       seeded
       products seeded
       users seeded
       added 68 packages in 75.215s
       
-----> Build
       Running build
       
       > scissors-palace@0.1.0 build /tmp/build_cc6cc312
       > cd react-ui/ && npm run build
       
       
       > client@1.0.0 build /tmp/build_cc6cc312/react-ui
       > craco build
       
       Creating an optimized production build...
       Compiled successfully.
       
       File sizes after gzip:
       
         133.76 KB (+91.8 KB)  build/static/js/2.b084d92d.chunk.js
         9.81 KB (+9.33 KB)    build/static/js/main.33d3c584.chunk.js
         4.43 KB (+2.31 KB)    build/static/css/main.d7f9a0fe.chunk.css
         772 B                 build/static/js/runtime-main.7545a8a1.js
       
       The project was built assuming it is hosted at /.
       You can control this with the homepage field in your package.json.
       
       The build folder is ready to be deployed.
       You may serve it with a static server:
       
         npm install -g serve
         serve -s build
       
       Find out more about deployment here:
       
         https://cra.link/deployment
       
       
-----> Caching build
       - node_modules
       
-----> Pruning devDependencies
       removed 57 packages and audited 11 packages in 2.491s
       
       6 packages are looking for funding
         run `npm fund` for details
       
       found 0 vulnerabilities
       
       
-----> Build succeeded!
-----> App not compatible with buildpack: https://github.com/mars/heroku-cra-node
       bash: /tmp/codon/tmp/buildpacks/d07ae047a3685d9cfb39224105301a7dbdbfbe9c/bin/detect: No such file or directory
       More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
 !     Push failed
`

**Comment by ferick8246** [comment]
https://github.com/ferick8246/Scissors-Palace

**Comment by mars** [comment]
[CRACO seems cause issues](https://github.com/mars/create-react-app-buildpack/issues/189#issuecomment-861667126) with create-react-app-buildpack.

**Comment by mars** [comment]
```
-----> Using buildpacks:
1. heroku/nodejs
2. https://github.com/mars/heroku-cra-node
```

This repo is not a buildpack. Remove it from your app `heroku buildpacks:remove https://github.com/mars/heroku-cra-node`, and then ensure the app follows the structure & config explained in the [README](https://github.com/mars/heroku-cra-node/blob/master/README.md).
